spring:
  application:
    name: ken_lapis
  jpa:
    show-sql: true
    format-sql: true
#    hibernate:
#      ddl-auto: create
#      order_inserts: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ken_lapis
    username: postgres
    password: DADOS
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  flyway:
    baseline-on-migrate: true
    enabled: true
#      locations: classpath:db/migration
    baseline-version: 1